import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Navbar from './components/Navbar';
import NavbarMenu from './components/NavbarMenu';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black min-h-screen flex flex-col`}
      >
        <NavbarMenu />
        <main className="flex-1 overflow-y-auto">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
